version: "3.8"

services:
  frontend:
    build: frontimage
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage

  backend:
    build: backimage
    ports:
      - 8000:8000
    volumes:
      - ./storage:/storage
