version: "3.9"

services:
  frontend:
    build: adsum_frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    volumes:
        - ./storage:/storage

  backend:
    build: adsum_backend
    ports:
      - 8000:8000
    volumes:
      - ./storage:/storage
